version: 2.1

description: Tasks for managing NPM modules in CircleCI builds

display:
  home_url: "https://github.com/boxt/orbs"
  source_url: "https://github.com/boxt/npm-orb/blob/main/config.yml"

commands:
  cache-read:
    parameters:
      version:
        description: Version of the cache to restore
        type: string
        default: "v1"
    steps:
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - npm-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-cache-v1-{{ .Branch }}-
            - npm-cache-v1-
          name: Restore NPM cache

  cache-write:
    parameters:
      version:
        description: Version of the cache to save
        type: string
        default: "v1"
    steps:
      - save_cache:
          key: npm-cache-v1-{{ .Branch }}-{{checksum "package-lock.json" }}
          name: Save NPM cache
          paths:
            - ~/.cache
            - ./node_modules

  install:
    steps:
      - run: "npm install"
